name: AutoRun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r reqirements.txt

    - name: Run unit tests
      run: |
        python unittest_calc.py

    - name: Build installer
      run: |
        python setup.py sdist bdist_wheel

    - name: Install application
      run: |
        pip install calc.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/